name: Ruby

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:14-alpine
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    env:
      RAILS_ENV: test
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      RUBYOPT: -EUTF-8 -W:deprecated
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?encoding=utf8&pool=5&timeout=5000

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install packages
        run: |
          sudo apt-get -yqq install libgbm1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install

      - name: Setup database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: assets:precompile
        run: bin/rails assets:precompile

      - name: Run rspec
        env:
          DISABLE_SPRING: 1
          COVERAGE: true
        run: |
          bundle exec rspec -f j -o tmp/rspec_results.json -f p

      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
        if: always()

      # Run bundler-audit（gemの脆弱性チェック）
      - name: Run bundler audit
        run: bundle exec bundle-audit check --update
        if: always()

      # Run brakeman（セキュリティの脆弱性チェック）
      - name: Run brakeman
        run: bundle exec brakeman -qz -A --skip-files /doc/
        if: always()

      - name: Archive screenshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: tmp/screenshots/*
        if: always()

      - name: Log artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log/test.log
        if: always()

      - uses: k1LoW/octocov-action@v0

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
        if: always()